[package]
name = "biosim_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.1"
rand = "0.8.5"
rand_pcg = "0.3.1"
thiserror = "1.0.51"

[profile.dev]
debug = 1
